### ISSUE TITLE
why getPathsForKey removed in production

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-view-scope#171]
why is this function removed in production code?
https://github.com/canjs/can-view-scope/blob/master/can-view-scope.js#L431

i got an error if i make a build.

i am not sure. but maybe this is related to https://github.com/donejs/autorender/commit/720af842ec204077a51be780df17bf4f5a2f63b4
i have a `<x-login app:from="scope.vm"></x-login>` and can tries to fetch `vm` with the function `getPathsForKey`. in production the functions is emtpy so i got this error.

```
steal.production.js:11 Potentially unhandled rejection [4] TypeError: Cannot read property 'vm' of undefined
    at Scope.hasKey (http://localhost:8080/dist/bundles/medicalpad/index.js:10858:30)
    at Object.hasKey (http://localhost:8080/dist/bundles/medicalpad/index.js:3694:31)
    at objHasKeyAtIndex (http://localhost:8080/dist/bundles/medicalpad/index.js:9855:89)
    at Object.read (http://localhost:8080/dist/bundles/medicalpad/index.js:9895:28)
    at Scope.read (http://localhost:8080/dist/bundles/medicalpad/index.js:10671:47)
    at ScopeKeyData.read (http://localhost:8080/dist/bundles/medicalpad/index.js:10525:39)
    at Observation.onBound (http://localhost:8080/dist/bundles/medicalpad/index.js:6756:40)
    at KeyTree.add (http://localhost:8080/dist/bundles/medicalpad/index.js:6399:40)
    at Observation.on (http://localhost:8080/dist/bundles/medicalpad/index.js:6568:27)
    at Object.eval [as onValue] (http://localhost:8080/dist/bundles/medicalpad/index.js:3122:31)
```

cc @phillipskevin

**Comment by justinbmeyer** [comment]
That function should only be used by dev logging.

**Comment by pYr0x** [comment]
yeah, but it gets called from https://github.com/canjs/can-view-scope/blob/master/can-view-scope.js#L539

**Comment by justinbmeyer** [comment]
Why does that get called? Can you create a test of a template that would call that?

**Comment by pYr0x** [comment]
here is a demo https://github.com/pYr0x/view-scope-bug
